### PR TITLE
added cloud9 instructions and a case change for an issue i encountered in cloud9

### PR DESCRIPTION
**Pull request by matikin9**

### CODE REVIEW

**Review by xtine — APPROVED** [review]
Looks good. Did you want to remove the sudo pip3 instruction from general "Install dependencies" line since it's specified in this cloud9 section?

**Comment by matikin9** [comment]
Sounds good!  How does the workflow for an additional change work?  Do I merge this pull request and then open a new pull request with that change?

**Comment by xtine** [comment]
Just push another commit and it should auto-update this PR.

**Comment by matikin9** [comment]
WOAHHH, that's awesome!!!

**Pull request merged**
